import:
    - convesio/redis
services:
  node:
    source:
      type: docker
      # image: node:latest
      build: ./node-dockerfile
      # copy:
      #   - ./package.json:/usr/src/app/package.json
      #   - ./app.js:/usr/src/app/app.js
    environment:
      APPLICATION_TYPE: NODE
      DEVELOPMENT_MODE: development
      WORDPRESS_DB_HOST: "mysql"
      WORDPRESS_DB_NAME: "${my_database_name}"
      WORDPRESS_DB_USER: "${my_database_user}"
      WORDPRESS_DB_PASSWORD: "${my_database_pass}"
    route:
      - 00:3000/default
    ingress: true
    scale:
      minimum: 1
      maximum: 2
      triggers:
        - observe: cpu
          is_above: 70
          metric_type: avarage
          action: up
          cooldown: 300
        - observe: cpu
          is_below: 50
          metric_type: avarage
          action: down
          cooldown: 300
