services:
  node:
    source:
      type: docker
      image: node:latest
      copy:
        - ./package.json:/usr/src/app
        - ./app.js:/usr/src/app
      boot: apache2
    first_run: "npm start"
    environment:
      APPLICATION_TYPE: NODE
      DEVELOPMENT_MODE: development
      WORDPRESS_DB_HOST: "mysql"
      WORDPRESS_DB_NAME: "${my_database_name}"
      WORDPRESS_DB_USER: "${my_database_user}"
      WORDPRESS_DB_PASSWORD: "${my_database_pass}"
    # mount:
    #   - uploads:/var/www/html/wp-contents/uploads
    #   - cache:/var/cache/convesio
    route:
    #   - 8999:6500/https
    #   - 22:2222/ssh
      - 00:3000/default
    ingress: true
    scale:
      minimum: 1
      maximum: 2
      triggers:
        - observe: cpu
          is_above: 70
          metric_type: avarage
          action: up
          cooldown: 300
        - observe: cpu
          is_below: 50
          metric_type: avarage
          action: down
          cooldown: 300
